Firefly/Firefly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('developenv.urls')),
]

Firefly/developenv/urls.py
from django.urls import path
from . import views

app_name = 'developenv'

urlpatterns = [
    path("", views.index, name="dev_index"),
    path("status", views.car_status, name="dev_status"),
    path("command", views.car_command, name='dev_command')
]

Firefly/developenv/models.py
from django.db import models


# Create your models here.

class carStatus(models.Model):
    car_id = models.CharField(max_length=10, verbose_name="唯一标识ID")  #
    goal = models.CharField(max_length=10, verbose_name='目标地址代码')  # 0
    path_start = models.CharField(max_length=10)  # 0
    path_end = models.CharField(max_length=10)  # 0
    box = models.CharField(max_length=255)  # ['0'] * box_quantity
    created_time = models.DateField(auto_now=True)
    nav_status = models.CharField(max_length=10)  # 0
    nav_service = models.CharField(max_length=10)  # 0
    nav_location = models.CharField(max_length=255)  # [0., 0., 0.]

    class Meta:
        db_table = 'carstatus'

    def __str__(self):
        return "[{0}]-{1}".format(self.car_id, self.nav_location)


class Command(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='小车编号')
    type = models.CharField(max_length=1, verbose_name='命令类型')          # 对应一个参数类型表，前端实现数据字典管理
    param_1 = models.CharField(max_length=1, verbose_name='参数1')
    param_2 = models.CharField(max_length=1, verbose_name='参数2')
    is_accept = models.CharField(max_length=1, verbose_name='是否接受')

    class Meta:
        db_table = 'command'

    def __str__(self):
        return "[{0}]-{1}".format(self.id, self.type)

Firefly/developenv/views.py
from django.http import JsonResponse
from django.shortcuts import render

from developenv import models
from . import command

# Create your views here.
from django.views.decorators.csrf import csrf_exempt


def index(request):
    return render(request, 'developenv/index.html')


def car_status(request):
    return render(request, 'developenv/status.html')


@csrf_exempt
def car_command(request):
    if request.is_ajax():
        car = request.POST['car']
        car_type = request.POST['car_type']
        param_1 = request.POST['param_1']
        param_2 = request.POST['param_2']

        data = {
            "car": car,
            "car_type": car_type,
            "param_1": param_1,
            "param_2": param_2,
        }

        ret_data = {'ret_code': '200', 'ret_message': '接收成功!'}

        flag = command.accept_command(data)
        if flag:
            # 存储命令
            models.Command.objects.create(type=car_type, param_1=param_1, param_2=param_2, is_accept="1")
            return JsonResponse(ret_data)
        else:
            # 失败命令
            models.Command.objects.create(type=car_type, param_1=param_1, param_2=param_2, is_accept="0")
            ret_data['ret_code'] = '300'
            ret_data['ret_message'] = '接收失败!'
            return JsonResponse(ret_data)

    return render(request, 'developenv/command.html')

Firefly/developenv/templates/developenv/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}basepage{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="Content-Language" content="zh-CN"/>
    <meta name="Author" content="pinsily"/>
    <meta name="Copyright" content="pinsily.site"/>
    <meta name="keywords" content="robot expressage"/>
    <meta name="description" content="Firefly 开发人员专用"/>
    <link rel="Shortcut Icon" href="{% static 'developenv/imgs/favicon.ico' %}"/>


    <link type="text/css" rel="stylesheet" href="{% static 'developenv/css/bootstrap.min.css' %}"/> <!-- 4.1.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="{% static 'developenv/css/init.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'developenv/css/style.css' %}"/>

    <script type="text/javascript" src="{% static 'developenv/js/jquery.min.js' %}"></script>       <!-- 3.2.1 -->
    <script type="text/javascript" src="{% static 'developenv/js/popper.min.js' %}"></script>       <!-- 1.12.5 -->
    <script type="text/javascript" src="{% static 'developenv/js/bootstrap.min.js' %}"></script>    <!-- 4.1.0 -->


</head>
<body class="body">

<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            {% include 'developenv/slidbar.html' %}
        </div>
        <div class="col-9">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="header">
                            <div class="header-title">
                                <p>{% block header-title %}Home{% endblock %}</p>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-12">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>

Firefly/developenv/templates/developenv/command.html
{% extends 'developenv/base.html' %}

{% block title %}Command{% endblock %}
{% block header-title %}小车状态{% endblock %}

{% block content %}
    <div class="status-title">
        <p>发送命令</p>
    </div>
    <div class="command-form">
        <form action="{% url 'developenv:dev_command' %}" method="post">
            {% csrf_token %}
            <div class="form-group row">
                <label for="car" class="col-3 col-form-label">选择车辆</label>
                <div class="col-3">
                    <select class="form-control" id="car">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>

                <label for="A" class="col-3 col-form-label">命令 A</label>
                <div class="col-3">
                    <select class="form-control" id="A">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>

                <label for="B" class="col-3 col-form-label">命令 B</label>
                <div class="col-3">
                    <select class="form-control" id="B">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>

                <label for="C" class="col-3 col-form-label">命令 C</label>
                <div class="col-3">
                    <select class="form-control" id="C">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>
            </div>


            <div class="form-btn row text-center">
                <div class="col-12">
                    <button class="btn btn-primary" type="button" onclick="submitForm()">发送</button>
                    <button class="btn btn-default" type="reset">取消</button>
                </div>
            </div>
        </form>
    </div>

    <script type="text/javascript">

        function submitForm() {

            var url = "{% url 'developenv:dev_command' %}";
            var data = {
                car: $("#car").val(),
                car_type: $("#A").val(),
                param_1: $("#B").val(),
                param_2: $("#C").val(),
            };

            //console.log(data);
            //console.log(url);

            $.ajax({

                url: url,
                data: data,
                type: 'POST',
                dataType: 'json',
                success: function(data){
                    //console.log(data);
                    alert(data['ret_message']);
                },

            });
        }

    </script>
{% endblock %}

Firefly/developenv/templates/developenv/index.html
{% extends 'developenv/base.html' %}

{% block title %}index{% endblock %}
{% block header-title %}index{% endblock %}

Firefly/developenv/templates/developenv/slidbar.html
{% load static %}
<div class="slidbar">

    <div class="logo">
        <a href="#">
            <img src="{% static 'developenv/imgs/robot.png' %}" alt="home" class="rounded">
        </a>
    </div>

    <div class="slidbar-nav">
        <table class="slidbar-table">
            <tr>
                <th><i class="fa fa-home" aria-hidden="true"></i></th>
                <th><span class="hidden-xs hidden-sm"><a href="{% url 'developenv:dev_index' %}">Home</a></span></th>
            </tr>
            <tr>
                <th><i class="fa fa-tasks" aria-hidden="true"></i></th>
                <th><span class="hidden-xs hidden-sm"><a href="{% url 'developenv:dev_command' %}">Command</a></span></th>
            </tr>
            <tr>
                <th><i class="fa fa-bar-chart" aria-hidden="true"></i></th>
                <th><span class="hidden-xs hidden-sm"><a href="{% url 'developenv:dev_status' %}">Status</a></span></th>
            </tr>
            <tr>
                <th><i class="fa fa-user" aria-hidden="true"></i></th>
                <th><span class="hidden-xs hidden-sm">User</span></th>
            </tr>
            <tr>
                <th><i class="fa fa-calendar" aria-hidden="true"></i></th>
                <th><span class="hidden-xs hidden-sm">Calender</span></th>
            </tr>
            <tr>
                <th><i class="fa fa-cog" aria-hidden="true"></i></th>
                <th><span class="hidden-xs hidden-sm">Setting</span></th>
            </tr>
        </table>

    </div>
</div>

Firefly/developenv/templates/developenv/status.html
{% extends 'developenv/base.html' %}

{% block title %}status{% endblock %}
{% block header-title %}小车状态{% endblock %}

{% block content %}
    <div class="status-title">
        <p>小车状态</p>
    </div>
    <div class="status-table">
        <table class="table table-bordered table-hover">
            <thead class="thead">
            <tr>
                <th>id</th>
                <th>status</th>
                <th>goal</th>
                <th>path_start</th>
                <th>path_end</th>
                <th>box</th>
                <th>current</th>
                <th>nav_status</th>
                <th>nav_service</th>
                <th>nav_location</th>
            </tr>
            </thead>
            <tbody class="tbody">
            <tr>
                <td>1</td>
                <td>良好</td>
                <td>10</td>
                <td>0</td>
                <td>10</td>
                <td>0000000000</td>
                <td>time</td>
                <td>0</td>
                <td>1</td>
                <td>1</td>
            </tr>
            <tr>
                <td>1</td>
                <td>良好</td>
                <td>10</td>
                <td>0</td>
                <td>10</td>
                <td>0000000000</td>
                <td>time</td>
                <td>0</td>
                <td>1</td>
                <td>1</td>
            </tr>
            <tr>
                <td>1</td>
                <td>良好</td>
                <td>10</td>
                <td>0</td>
                <td>10</td>
                <td>0000000000</td>
                <td>time</td>
                <td>0</td>
                <td>1</td>
                <td>1</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}